// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableSites() {
  return window['go']['main']['App']['GetAvailableSites']();
}

export function GetItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetItems'](arg1, arg2, arg3);
}

export function GetNumItems(arg1, arg2) {
  return window['go']['main']['App']['GetNumItems'](arg1, arg2);
}

export function ParseLinksAndSaveToXlsx(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParseLinksAndSaveToXlsx'](arg1, arg2, arg3);
}
